-- Tabla de jugadores
CREATE TABLE Jugadores (
    JugadorId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- PK autogenerada
    Identificacion NUMBER UNIQUE NOT NULL,                     -- ID único (cédula)
    Nombre VARCHAR2(100) NOT NULL,                             -- nombre requerido
    Marcador NUMBER DEFAULT 0                                  -- inicia en 0
);
--------------------------------------------------------------------------------------------
-- Tabla de partidas
CREATE TABLE Partidas (
    PartidaId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- PK autogenerada
    Jugador1Id NUMBER NOT NULL,
    Jugador2Id NUMBER NOT NULL,
    FechaInicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,           -- se llena al crear
    Estado VARCHAR2(20) DEFAULT 'EN_CURSO',                    -- 'EN_CURSO'/'FINALIZADA'
    GanadorId NUMBER,                                          -- NULL si hay empate
    FOREIGN KEY (Jugador1Id) REFERENCES Jugadores(JugadorId),
    FOREIGN KEY (Jugador2Id) REFERENCES Jugadores(JugadorId),
    FOREIGN KEY (GanadorId) REFERENCES Jugadores(JugadorId)
);
--Recorre partidas sin número y les asigna 1, 2, 3, … según PartidaId.
DECLARE
  v_contador NUMBER := 1;
BEGIN
  FOR partida IN (SELECT PartidaId FROM Partidas WHERE NumeroVisible IS NULL ORDER BY PartidaId)
  LOOP
    UPDATE Partidas
    SET NumeroVisible = v_contador
    WHERE PartidaId = partida.PartidaId;

    v_contador := v_contador + 1;
  END LOOP;
  ------------------------------------------------------------------------------------------------
-- Tabla de movimientos por partida, prueba
CREATE TABLE Movimientos (
    MovimientoId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- PK autogenerada
    PartidaId NUMBER NOT NULL,                                    -- a qué partida
    JugadorId NUMBER NOT NULL,                                    -- quién jugó
    Columna VARCHAR2(1) NOT NULL, -- A-G
    Fila NUMBER NOT NULL,         -- 1-6
    Turno NUMBER NOT NULL,        -- número de jugada
    FechaHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PartidaId) REFERENCES Partidas(PartidaId),
    FOREIGN KEY (JugadorId) REFERENCES Jugadores(JugadorId)
);
  ------------------------------------------------------------------------------------------------
-- 3. Crear tabla con IDENTITY reiniciado 
CREATE TABLE Partidas (
  PartidaId  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- PK auto; contador reiniciable y asignable manualmente
  Jugador1Id NUMBER,                                              -- Id del jugador 1 (agrega FK aparte si la necesitas)
  Jugador2Id NUMBER,                                              -- Id del jugador 2 (agrega FK aparte si la necesitas)
  Estado     VARCHAR2(20),                                        -- Estado SIN default aquí (p.ej. 'EN_CURSO'/'FINALIZADA')
  GanadorId  NUMBER,                                              -- Id del ganador; puede ser NULL en empate
  FechaInicio DATE                                                -- Solo fecha (si quieres hora usa TIMESTAMP)
);

ALTER TABLE Partidas ADD NumeroVisible NUMBER; -- Número “bonito” para UI (Partida #1, #2, ...)

---------------------------------------------------------------------------------
-- Secuencia 
CREATE SEQUENCE SecuenciaPartidas START WITH 1 INCREMENT BY 1;