-- Tabla de jugadores
CREATE TABLE Jugadores (
    JugadorId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Identificacion NUMBER UNIQUE NOT NULL,
    Nombre VARCHAR2(100) NOT NULL,
    Marcador NUMBER DEFAULT 0
);
CREATE SEQUENCE SecuenciaPartidas START WITH 1 INCREMENT BY 1;
-- Tabla de partidas
CREATE TABLE Partidas (
    PartidaId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Jugador1Id NUMBER NOT NULL,
    Jugador2Id NUMBER NOT NULL,
    FechaInicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Estado VARCHAR2(20) DEFAULT 'EN_CURSO', -- 'EN_CURSO', 'FINALIZADA'
    GanadorId NUMBER, -- Puede ser NULL en caso de empate
    FOREIGN KEY (Jugador1Id) REFERENCES Jugadores(JugadorId),
    FOREIGN KEY (Jugador2Id) REFERENCES Jugadores(JugadorId),
    FOREIGN KEY (GanadorId) REFERENCES Jugadores(JugadorId)
);
ALTER TABLE Partidas ADD NumeroVisible NUMBER;
DECLARE
  v_contador NUMBER := 1;
BEGIN
  FOR partida IN (SELECT PartidaId FROM Partidas WHERE NumeroVisible IS NULL ORDER BY PartidaId)
  LOOP
    UPDATE Partidas
    SET NumeroVisible = v_contador
    WHERE PartidaId = partida.PartidaId;

    v_contador := v_contador + 1;
  END LOOP;
-- Tabla de movimientos por partida, prueba
CREATE TABLE Movimientos (
    MovimientoId NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PartidaId NUMBER NOT NULL,
    JugadorId NUMBER NOT NULL,
    Columna VARCHAR2(1) NOT NULL, -- A-G
    Fila NUMBER NOT NULL,         -- 1-6
    Turno NUMBER NOT NULL,        -- Número de jugada
    FechaHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PartidaId) REFERENCES Partidas(PartidaId),
    FOREIGN KEY (JugadorId) REFERENCES Jugadores(JugadorId)
);
----Cambios de tabla Partidas para permitir IDENTITY
-- 1. Borrar datos
DELETE FROM Movimientos;
DELETE FROM Partidas;
COMMIT;

-- 2. Borrar tabla para reiniciar ID
DROP TABLE Partidas CASCADE CONSTRAINTS;

-- 3. Crear tabla con IDENTITY reiniciado
CREATE TABLE Partidas (
  PartidaId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Jugador1Id NUMBER,
  Jugador2Id NUMBER,
  Estado VARCHAR2(20),
  GanadorId NUMBER,
  FechaInicio DATE
);
